[package]
name = "xtask"
description = "Repository maintenance tasks for TomlSmith"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
publish = false

[dependencies]
ungrammar.workspace = true

[lints]
workspace = true
