[package]
name = "tomlsmith-test-decoder"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
publish = false

[dependencies]
serde_json.workspace = true
tomlsmith.workspace = true

[lints]
workspace = true
