#![forbid(unsafe_code)]

use std::{error::Error, fmt::Write as _, path::Path, process::ExitCode};

fn main() -> ExitCode {
    match run() {
        Ok(()) => ExitCode::SUCCESS,
        Err(error) => {
            eprintln!("xtask: {error}");
            ExitCode::FAILURE
        }
    }
}

fn run() -> Result<(), Box<dyn Error>> {
    let arguments = std::env::args().skip(1).collect::<Vec<_>>();
    let command = arguments.first().map_or("codegen", String::as_str);
    if command != "codegen" {
        return Err(format!("unknown command `{command}`; expected `codegen`").into());
    }
    let workspace = Path::new(env!("CARGO_MANIFEST_DIR")).join("..");
    let grammar_source = std::fs::read_to_string(workspace.join("crates/tomlsmith/syntax.ungram"))?;
    let grammar = grammar_source.parse::<ungrammar::Grammar>()?;
    let generated = generate(&grammar);
    let destination = workspace.join("crates/tomlsmith/src/syntax/ast/generated.rs");
    if arguments.iter().any(|argument| argument == "--check") {
        let existing = std::fs::read_to_string(&destination).unwrap_or_default();
        if existing != generated {
            return Err(format!(
                "{} is stale; run `cargo run -p xtask -- codegen`",
                destination.display()
            )
            .into());
        }
    } else {
        std::fs::write(destination, generated)?;
    }
    Ok(())
}

fn generate(grammar: &ungrammar::Grammar) -> String {
    const CONCRETE: &[&str] = &[
        "Root",
        "KeyValue",
        "Key",
        "Value",
        "Table",
        "ArrayTable",
        "Array",
        "InlineTable",
    ];

    let mut output = String::from(
        "// This file is generated by `cargo run -p xtask -- codegen`.\n// Do not edit it by hand.\n\n#![allow(dead_code)]\n\nuse super::{SyntaxKind, SyntaxNode};\n\npub(crate) trait AstNode: Clone {\n    fn can_cast(kind: SyntaxKind) -> bool;\n    fn cast(syntax: SyntaxNode) -> Option<Self>;\n    fn syntax(&self) -> &SyntaxNode;\n}\n\n",
    );

    for node in grammar.iter() {
        let name = &grammar[node].name;
        if !CONCRETE.contains(&name.as_str()) {
            continue;
        }
        writeln!(
            output,
            "#[derive(Clone, Debug)]\npub(crate) struct {name} {{\n    syntax: SyntaxNode,\n}}\n\nimpl AstNode for {name} {{\n    fn can_cast(kind: SyntaxKind) -> bool {{\n        kind == SyntaxKind::{name}\n    }}\n\n    fn cast(syntax: SyntaxNode) -> Option<Self> {{\n        Self::can_cast(syntax.kind()).then_some(Self {{ syntax }})\n    }}\n\n    fn syntax(&self) -> &SyntaxNode {{\n        &self.syntax\n    }}\n}}\n"
        )
        .expect("writing to a string cannot fail");
    }

    for node in grammar.iter() {
        let name = &grammar[node].name;
        if CONCRETE.contains(&name.as_str()) {
            continue;
        }
        let Some(variants) = node_alternatives(grammar, &grammar[node].rule) else {
            continue;
        };
        if variants.is_empty()
            || !variants
                .iter()
                .all(|variant| CONCRETE.contains(&variant.as_str()))
        {
            continue;
        }

        writeln!(output, "#[derive(Clone, Debug)]\npub(crate) enum {name} {{")
            .expect("writing to a string cannot fail");
        for variant in &variants {
            writeln!(output, "    {variant}({variant}),").expect("writing to a string cannot fail");
        }
        output.push_str("}\n\n");
        writeln!(output, "impl {name} {{").expect("writing to a string cannot fail");
        output.push_str("    pub(crate) fn cast(syntax: SyntaxNode) -> Option<Self> {\n");
        output.push_str("        match syntax.kind() {\n");
        for variant in &variants {
            writeln!(
                output,
                "            SyntaxKind::{variant} => {variant}::cast(syntax).map(Self::{variant}),"
            )
            .expect("writing to a string cannot fail");
        }
        output.push_str("            _ => None,\n        }\n    }\n\n");
        output.push_str("    pub(crate) fn syntax(&self) -> &SyntaxNode {\n        match self {\n");
        for variant in &variants {
            writeln!(
                output,
                "            Self::{variant}(node) => node.syntax(),"
            )
            .expect("writing to a string cannot fail");
        }
        output.push_str("        }\n    }\n}\n\n");
    }

    output.truncate(output.trim_end().len());
    output.push('\n');
    output
}

fn node_alternatives(grammar: &ungrammar::Grammar, rule: &ungrammar::Rule) -> Option<Vec<String>> {
    let ungrammar::Rule::Alt(alternatives) = rule else {
        return None;
    };
    alternatives
        .iter()
        .map(|alternative| match alternative {
            ungrammar::Rule::Node(node) => Some(grammar[*node].name.clone()),
            _ => None,
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::generate;

    #[test]
    fn grammar_generates_typed_nodes_and_sum_types() {
        let grammar = include_str!("../../crates/tomlsmith/syntax.ungram")
            .parse::<ungrammar::Grammar>()
            .expect("valid ungrammar");

        let generated = generate(&grammar);

        assert!(generated.contains("pub(crate) struct Root"));
        assert!(generated.contains("pub(crate) struct KeyValue"));
        assert!(generated.contains("pub(crate) enum Statement"));
        assert!(generated.contains("SyntaxKind::InlineTable"));
    }
}
